site_name: Yama Jiang
site_url: https://sitename.example
theme:
  name: material 
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: fontawesome/solid/computer
  features:
    - navigation.footer
  palette: 
    #Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: deep purple
      accent: indigo

    #Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: DaLightrk mode
      primary: deep purple
      accent: indigo

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
extra:
  social:
    - icon: simple/github
      link: https://github.com/yamajiang
    - icon: simple/linkedin
      link: https://www.linkedin.com/in/yamajiang/

copyright: Copyright &copy; 2024 Yama Jiang