site_name: Yama Jiang
site_url: https://yamajiang.dev
theme:
  name: material 
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: fontawesome/solid/computer
  features:
    - navigation.footer
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs 
    - navigation.tabs.sticky
    - navigation.sections
    
   
  palette: 
    #Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: blue grey
      accent: indigo

    #Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: DaLightrk mode
      primary: blue grey
      accent: indigo


nav:
- Introduction: index.md
- Documentation: 
  - Info: notes/docs.md
  - Python Review: notes/Python Review.md
- Projects: 
  - Info: projects/Info.md
  - NavX: projects/NavX.md
  - Pokébook: projects/Pokébook.md
  - MATE ROV: projects/MATEROV.md
  - Okayama: projects/Okayama.md
  - FaceGuard: projects/FaceGuard.md
  - Flappy Bird: projects/FlappyBird.md
  - Minesweeper: projects/Minesweeper.md

  



markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yamajiang
    - icon: fontawesome/brands/linkedin-in
      link: https://www.linkedin.com/in/yamajiang/

copyright: Copyright &copy; 2025 Yama Jiang